import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>
      <div className={styles.home}>
        <p style={{color:"white", fontSize:"2rem", fontWeight:"400"}}>HELLO</p>
      </div>
      
    </div>
  )
}
